name: OwnGarden
main: fr.skyost.owngarden.OwnGarden
description: Grow custom trees !
version: ${version}
authors: [Skyost, LaBoulangerie, Clem, Red69_Leaf]
website: https://github.com/LaBoulangerie/OwnGarden
api-version: 1.21.11
commands:
  owngarden:
    description: Main command of OwnGarden.
    aliases:
     - own-garden
    usage: /owngarden
    permission: owngarden.command
permissions:
  owngarden.command:
    default: op
    description: Allows you to use /owngarden.
  owngarden.reload:
    default: op
    description: Allows you to reload the configuration and structures.