name: OwnGarden
main: fr.skyost.owngarden.OwnGarden
description: Grow custom trees !
version: 0.3.0
authors: [Skyost, LaBoulangerie, Clem]
website: https://github.com/LaBoulangerie/OwnGarden
api-version: 1.21
commands:
  owngarden:
    description: Main command of OwnGarden.
    aliases:
     - own-garden
    usage: /owngarden
    permission: owngarden.command
permissions:
  owngarden.command:
    default: op
    description: Allows you to use /owngarden.